version: '3.8'

services:
  web_falta:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume_falta:/home/faltaAbonada/web/staticfiles
      #- media_volume:/home/faltaAbonada/web/mediafiles
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db_falta
      - redis_falta

  redis_falta:
    image: redis:6.2-alpine
    #restart: always
    expose:
      - 6379
    command: redis-server

  db_falta:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_falta:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx_falta:
    build: ./nginx
    volumes:
      - static_volume_falta:/home/faltaAbonada/web/staticfiles
      #- media_volume:/home/proto_fiesta/web/mediafiles
    ports:
      - '1337:80'
    depends_on:
      - web_falta

volumes:
  postgres_data_falta:
  static_volume_falta:
  #media_volume: