# Generated by Django 4.1.2 on 2022-10-25 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faltas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faltaabonada',
            options={'ordering': ['-data_falta'], 'verbose_name_plural': 'Faltas Abonadas'},
        ),
    ]
