# Generated by Django 4.1.2 on 2022-10-26 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faltas', '0002_alter_faltaabonada_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faltaabonada',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faltas_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário'),
        ),
    ]
