# Generated by Django 4.1.2 on 2022-10-26 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faltas', '0005_alter_faltaabonada_funcionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faltaabonada',
            options={'ordering': ['funcionario', '-data_falta'], 'verbose_name_plural': 'Faltas Abonadas'},
        ),
    ]
